<a href="https://colab.research.google.com/github/chalarm1405/DWDM21_/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np # เป็น package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข ที่อยู่ในรูปของ Matrix

#Numpy Array

สร้าง Numpy Array (Matrix)

In [2]:
np_a = np.array([[1,2,3],[4,5,6]]) # สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [3]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np_a.shape # ตรวจสอบขนาดของ Matrix

(2, 3)

In [5]:
np_b = np.array([[1,4],[2,5],[3,6]]) # สร้าง numpy array ที่มี 3 แถว 2 หลัก
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
np_a.T  # Transpose - สลับแถวเป็นหลัก หลักเป็นแถว

array([[1, 4],
       [2, 5],
       [3, 6]])

#สร้าง matrix เริ่มต้น (zeros, ones)

In [7]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np_200 = 200*np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

#สร้าง matrix random

In [10]:
np.random.randn(5,5) # random เลขมาจาก normal distribution ที่มี mu = 0 std = 1

array([[ 1.14573688, -0.80551336,  0.24981168, -0.0212004 ,  1.62314006],
       [ 0.52498109, -1.12140752,  0.28060602,  0.21118464, -1.36692291],
       [ 2.0522981 ,  0.38352934,  0.68017467, -0.07900836,  0.5238377 ],
       [-3.01007309, -0.64068882, -2.39043318,  0.89926326,  0.72296566],
       [ 0.2080521 ,  0.42184923,  0.44355965,  1.80767918, -0.41561136]])

In [11]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu = 2 std = 5

array([[ 5.83335422, -7.2373307 , -0.98315339],
       [ 1.74149813,  7.42639677,  2.9002638 ],
       [ 2.78640929,  2.88999187, -6.62467455]])

In [12]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็มระหว่าง 5 ถึง 11 [5,11) ขนาด (4x5)

array([[ 5,  8,  7,  9, 10],
       [10,  6,  7,  7, 10],
       [ 6,  7,  9,  9,  7],
       [10, 10,  5,  7,  8]])

In [13]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np_a.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
1 + np_a # add scalar to matrix จะบวกไปทุกๆตัวใน matrix

array([[2, 3, 4],
       [5, 6, 7]])

In [16]:
2*np_a # multiply scalar to matrix จะคูณไปทุกๆตัวของ matrix

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [17]:
np_c = np.array([[6,5,4],[3,2,1]])
np_c

array([[6, 5, 4],
       [3, 2, 1]])

In [18]:
np_a + np_c # adding matrix to matrix

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np_a.shape

(2, 3)

In [20]:
np_c.shape

(2, 3)

In [21]:
np_c.T.shape

(3, 2)

In [22]:
np.dot(np_a,np_c.T) # multipling matrix to matrix (a,b) x (b,c) = (a,c)

array([[28, 10],
       [73, 28]])

#Indexing & Slicing ( Index - ชี้, Slice - ตัด )

In [23]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np_a[1,1] # เริ่มนับตั้งแต่แถวที่ 0 หลักที่ 0

5

In [25]:
np_a[:2,:2]

array([[1, 2],
       [4, 5]])

#QUIZE

In [48]:
# np.min(np_a,axis=1)
min_all = np.zeros(np_a.shape[0])

for col in range(np_a.shape[1]):
    for row in range(np_a.shape[0]):
        min_all[row] = min(np_a[row])
print(min_all)

[1. 4.]
